# Generated by Django 5.1.2 on 2024-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='is_predicted',
            field=models.BooleanField(default=False),
        ),
    ]
