name: Deploy Django App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t my-django-app .

      - name: Push to Docker Hub (optional)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-django-app myusername/my-django-app:latest
          docker push myusername/my-django-app:latest

      - name: Deploy to AWS (e.g., Elastic Beanstalk)
        run: |
          # Deploying commands for Elastic Beanstalk or your chosen method
          eb init -p docker my-django-app
          eb deploy
